version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes: 
      - db-data:/var/lib/mysql

volumes: 
  db-data: